dataset_configs:

    train_ft_path: data/DFMAD-70/features/i3d_rgb_feat
    test_ft_path: data/DFMAD-70/features/i3d_rgb_feat

    train_dict_path: data/dfmad_train_prop_dict.pkl
    val_dict_path: data/dfmad_val_prop_dict.pkl
    test_dict_path: data/dfmad_test_prop_dict.pkl
    train_prop_file: data/DFMAD-70/proposals/dfmad_bmn_train_100_proposal_list.txt
    test_prop_file: data/DFMAD-70/proposals/dfmad_bmn_test_100_proposal_list.txt

    training_epoch_multiplier: 20
    testing_epoch_multiplier: 1

    fg_iou_thresh: 0.7
    bg_iou_thresh: 0.01
    incomplete_iou_thresh: 0.3
    bg_coverage_thresh: 0.02
    incomplete_overlap_thresh: 0
    prop_per_video: 8
    fg_ratio: 1
    bg_ratio: 1
    incomplete_ratio: 6
    iou_threshold: 0.7
    dis_threshold: 0
    starting_ratio: 0.5
    ending_ratio: 0.5


graph_configs:
    adj_num: 21
    child_num: 4
    iou_num: 8
    dis_num: 2

model_configs:
    num_class: 3
    act_feat_dim: 2048
    comp_feat_dim: 6144
    dropout: 0.8
    gcn_dropout: 0.7


evaluation:
    top_k: 30
    nms_threshold: 0.2

